#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged
npm run lint-staged

# Check if lint-staged passed, and if not, exit and prevent commit
if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting commit."
  exit 1
fi
